### ISSUE TITLE
capability to send message to server via onopen and onclose?

### ISSUE THREAD

**Issue by momozor** [joaotavora/hunchensocket#26]
Hi.

I''m not sure how to make the server to receive a message for `onopen` and `onclose` as well? I want the client to send data to server so the server can send it back to all connected client (aka broadcast).

For example, client sends `{username: 'user1'}` with onopen trigger.
server should receive via `hunchensocket:client-connected` and broadcast the message to all clients.

The problem is, it seems if I make the client send data to server via onopen, the server wouldn't know and it will direct it to `hunchensocket:text-messaged-received` instead.

Thanks

**Comment by skidd0** [comment]
I believe this is intended behavior.

The `onopen` trigger can be used to send data to the server after a connection has been established, guaranteeing that the connection is setup and ready for data. As noted in [this MDN page](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications#Sending_data_to_the_server), creating a websocket connection is asynchronous. Sending data immediately after attempting to create a connection can sometimes result in a failure because the connection may not yet be ready or may have failed. `onopen` only triggers once a connection is set, avoiding this potential issue, but is not part of the connection creation process thus would not register on `client-connected`

Is there any issue with using the `text-message-received` method to broadcast your data?

**Comment by momozor** [comment]
@skidd0 Hi thanks for the information. I think I've been using websockets wrong. Currently there is no issue with `text-message-received`. Thanks for your help.
